name: Déploiement O2Switch

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Déployer via FTP
    runs-on: ubuntu-latest
    
    steps:
      # 1. Récupérer le code
      - name: Checkout du code
        uses: actions/checkout@v4
      
      # 2. Déployer via FTP
      - name: Déployer sur O2Switch
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          local-dir: ./
          server-dir: /oloustream/
          exclude: |
            **/.git*
            **/.git*/**
            **/venv/**
            **/env/**
            **/__pycache__/**
            **/*.pyc
            **/db.sqlite3
            **/.env
            **/staticfiles/**
            **/media/**
            **/.github/**
            **/logs/*.log